# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GPS-Point-Cluster
version:      0.05
version_from: lib/GPS/Point/Cluster.pm
installdirs:  site
requires:
    DateTime:                      0
    Geo::Inverse:                  0.05
    GPS::Point:                    0.02
    strict:                        0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
